@include('players.new')
@include('equipos.new')
@include('paises.new')
@include('posiciones.new')
@include('tipos-competencia.new')
@include('tipos-competencia.show-pop-up')
@include('competitions.new')
@include('competition-formats.new')
@include('alignment-types.new')
@include('sanction-types.new')

