@include('jugadores.new')
@include('equipos.new')
@include('paises.new')
@include('posiciones.new')
@include('tipos-competencia.new')
@include('competencias.new')
@include('tipos-competencia.show-pop-up')